# Generated by Django 3.2 on 2021-12-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0004_alter_cuadro_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadro',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
